### ISSUE TITLE
Application crash when using flutter beta channel or flutter version newer than 1.10.15

### ISSUE THREAD

**Issue by ekasetiawans** [go-flutter-desktop/go-flutter#321]
I use flutter beta channel (version 1.11.0).
I have trying in Windows, Linux, and Macos.

This is the logs shown on terminal.

```
poetra@macbook-pro my_app % hover run
hover: Using engine from cache
hover: Cleaning the build directory
hover: Bundling flutter app
Running "flutter pub get" in my_app...                     0.5s
hover: Checking available release on Github
hover: Compiling 'go-flutter' and plugins
github.com/go-gl/glfw/v3.2/glfw
# github.com/go-gl/glfw/v3.2/glfw
ld: warning: directory not found for option '-Lbuild/outputs/darwin'
ld: warning: directory not found for option '-Fbuild/outputs/darwin'
# github.com/go-gl/glfw/v3.2/glfw
In file included from /Users/poetra/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20191125211704-12ad95a8df72/v3.2/glfw/c_glfw_darwin.go:8:
/Users/poetra/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20191125211704-12ad95a8df72/v3.2/glfw/glfw/src/cocoa_window.m:989:9: warning: multiple methods named 'center' found [-Wobjc-multiple-method-names]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSCollectionViewCompositionalLayout.h:601:19: note: using
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:312:1: note: also found
github.com/go-flutter-desktop/go-flutter/internal/opengl
github.com/go-flutter-desktop/go-flutter
github.com/go-flutter-desktop/plugins/shared_preferences
github.com/myapp/desktop/cmd
hover: Successfully compiled
hover: Build finished, starting app...
hover: Running my_app in debug mode
flutter: Observatory listening on http://127.0.0.1:50300/J2ItCCr5KNQ=/
go-flutter: no handler found for channel flutter/isolate
[ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!

[FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp(95)] nTypefaces == 0
hover: App 'my_app' exited with error: signal: abort trap
```

**Comment by pchampio** [comment]
https://github.com/flutter/flutter/issues/45892
https://github.com/flutter/flutter/issues/26108
https://github.com/flutter/flutter/issues/8403
https://github.com/flutter/flutter/issues/26168

What is the content of pubspec.yaml?

**Comment by pchampio** [comment]
Does this error happens with one of our https://github.com/go-flutter-desktop/examples?

**Comment by ekasetiawans** [comment]
> [flutter/flutter#45892](https://github.com/flutter/flutter/issues/45892)
> [flutter/flutter#26108](https://github.com/flutter/flutter/issues/26108)
> [flutter/flutter#8403](https://github.com/flutter/flutter/issues/8403)
> [flutter/flutter#26168](https://github.com/flutter/flutter/issues/26168)
> 
> What is the content of the pubspec.yaml file?

is is my pubspec.yaml 

```
name: my_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+4
  intl: any
  flutter_svg: any
  draggable_scrollbar: ^0.0.4
  http: any
  provider: ^3.1.0
  autocomplete_textfield: ^1.7.3
  auto_size_text: ^2.1.0
  shimmer: ^1.0.1
  flutter_masked_text: ^0.8.0
  dart_ping: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 200
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-RegularItalic.ttf
          style: italic
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Gobold
      fonts:
        - asset: fonts/Gobold Regular.otf
    - family: Digital7
      fonts:
        - asset: fonts/digital7.ttf
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
    - family: NebulousContent
      fonts:
        - asset: fonts/NebulousContent.otf
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Medium.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Light.ttf
          weight: 300
        - asset: fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Light.ttf
          weight: 300
        - asset: fonts/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Rubik-Regular.ttf
          weight: 400
        - asset: fonts/Rubik-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Rubik-Black.ttf
          weight: 900
        - asset: fonts/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
    - family : SFProDisplay
      fonts:
        - asset: fonts/SFProDisplay-Thin.ttf
          weight: 100
        - asset: fonts/SFProDisplay-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/SFProDisplay-Ultralight.ttf
          weight: 200
        - asset: fonts/SFProDisplay-UltralightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/SFProDisplay-Light.ttf
          weight: 300
        - asset: fonts/SFProDisplay-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: fonts/SFProDisplay-RegularItalic.ttf
          style: italic
          weight: 400
        - asset: fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: fonts/SFProDisplay-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: fonts/SFProDisplay-SemiboldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/SFProDisplay-Bold.ttf
          weight: 700
        - asset: fonts/SFProDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/SFProDisplay-Heavy.ttf
          weight: 800
        - asset: fonts/SFProDisplay-HeavyItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/SFProDisplay-Black.ttf
          weight: 900
        - asset: fonts/SFProDisplay-BlackItalic.ttf
          weight: 900
          style: italic

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
