### ISSUE TITLE
Cannot get plugins when pubspec.yaml contains git url

### ISSUE THREAD

**Issue by ohsory1324** [go-flutter-desktop/go-flutter#442]
Hi, I have my own flutter plugin in gitlab and this is a part of my `pubspec.yaml`.
```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  spotu_auth:
    git:
      url: git@gitlab.com:spotu/flutter/plugin/spotu_auth.git
```

When I run `hover plugins get` command to get plugins, I get an error attached below.
I think yaml parser has a problem to parse git url.

## Hover doctor

```
$ hover doctor
hover: Hover version v0.41.5 running on darwin
hover: Sharing flutter version
Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (10 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1
hover: Flutter engine commit: https://github.com/flutter/engine/commit/540786dd51f112885a89792d678296b95e6622e5
hover: Finding out the C compiler version
Apple clang version 11.0.3 (clang-1103.0.32.59)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
hover: Sharing the content of go.mod
module spotuprofessional/go

go 1.14

require (
	github.com/go-flutter-desktop/go-flutter v0.40.1
	github.com/go-flutter-desktop/plugins/path_provider v0.4.0
	github.com/go-flutter-desktop/plugins/shared_preferences v0.4.3
	github.com/go-flutter-desktop/plugins/video_player v0.0.3
	github.com/pkg/errors v0.9.1
)
hover: Sharing the content of hover.yaml
application-name: ""
executable-name: ""
package-name: ""
license: ""
target: lib/main_desktop.dart
branch: ""
cache-path: ""
opengl: ""
engine-version: ""
hover: Sharing the content of go/cmd
go/cmd/import-path_provider-plugin.go	go/cmd/import-shared_preferences-plugin.go	go/cmd/import-video_player-plugin.go	go/cmd/main.go	go/cmd/options.go
```

## Error output

Using `hover plugins get` to get plugins, I get the following
error:

```log
hover: failed to parse URL from string %sgit@gitlab.com:spotu/flutter/plugin/spotu_auth.git: parse "git@gitlab.com:spotu/flutter/plugin/spotu_auth.git": first path segment in URL cannot contain colon
```
